baseURL = 'https://www.massprov.org/'
languageCode = 'en-us'
title = 'MassProv'
theme = 'massprov'

# This is used to mark html content as safe which is required for implamenting the iframe shortcode for the calender
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[pagination]
pagerSize = 6 # this is set low for demonstrating with dummy content. Set to a higher number

[params]
author = "MassProv"
favicon = "/images/massprove_small_logo_v2.png"
site_logo = "/images/massprove_symbol_logo_v2.png"
description = "MassProv is a nonprofit community connecting improvisers across Massachusetts with shows, jams, resources, and support."
